### ISSUE TITLE
Open an AUR package

### ISSUE THREAD

**Issue by albfan** [sjewo/pgrouting-pkgbuild#1]
Existing AUR package is for pgrouting 2.x

https://aur.archlinux.org/packages/pgrouting/

Your instructions are for pgrouting 1.05.

Many one could benefith from this AUR package

**Comment by sjewo** [comment]
According to upstream the problems with boost are fixed in prgrouting 2.0. Is there any need for the old package version?

**Comment by albfan** [comment]
To reproduce a system using with pgrouting 1.x

#2 solves that. I will use for my own, just want to share.

**Comment by albfan** [comment]
Done. I tried to upload your work, but AUR has a prehook to check .SRCINFO is included.

https://aur.archlinux.org/packages/pgrouting-1.x/

**Comment by sjewo** [comment]
Many thanks for uploading to AUR.
